#!/usr/bin/env bats

# Integration test: comet-speculate → /comet-open handoff
# Verifies: explore-findings.md generated by script can be detected
#           by /comet-open step 0a logic

setup() {
  export TMP_DIR="$(mktemp -d)"
  export SPECULATE_SCRIPT="$(pwd)/src/scripts/comet-speculate.sh"
  export CHANGE_DIR="$TMP_DIR/openspec/changes/test-change"
  mkdir -p "$CHANGE_DIR"
  cd "$TMP_DIR"
  mkdir -p openspec
}

teardown() {
  rm -rf "$TMP_DIR"
}

@test "explore-findings.md detection via /comet-open step 0a logic" {
  cat > "$TMP_DIR/input.yaml" << 'EOF'
topic: "测试功能的实现方式"
summary: "需要实现用户认证功能"
options:
  - name: "方案 A: JWT"
    pros:
      - "无状态"
    cons:
      - "无法撤销"
    effort: "2天"
  - name: "方案 B: Session"
    pros:
      - "可撤销"
    cons:
      - "需要存储"
    effort: "3天"
recommendation: "方案 A: JWT"
reason: "适合微服务架构"
EOF

  run bash "$SPECULATE_SCRIPT" \
    --mode full \
    --from-file "$TMP_DIR/input.yaml" \
    --output "$TMP_DIR/openspec/explore-findings.md"

  [ "$status" -eq 0 ]
  [ -f "$TMP_DIR/openspec/explore-findings.md" ]

  EXPLORE_FILE="openspec/explore-findings.md"
  [ -f "$EXPLORE_FILE" ]

  SUMMARY=$(grep -A 5 "^## Summary" "$EXPLORE_FILE" | tail -n +3 | head -1)
  echo "Summary: $SUMMARY"
  echo "$SUMMARY" | grep -q "用户认证"

  REC=$(grep -A 3 "^## Recommendation" "$EXPLORE_FILE" | tail -n +2)
  echo "Recommendation: $REC"
  echo "$REC" | grep -q "JWT"

  VERSION=$(grep "Version" "$EXPLORE_FILE" | grep -oE '[0-9]+')
  [ "$VERSION" -eq 1 ]
}

@test "explore-findings.md absent — silent skip" {
  EXPLORE_FILE="openspec/explore-findings.md"
  if [ -f "$EXPLORE_FILE" ]; then
    echo "ERROR: should not exist" >&2
    false
  fi
  [ ! -f "$EXPLORE_FILE" ]
}

@test "explore-findings.md with version > 1 — degrade gracefully" {
  cat > "$TMP_DIR/openspec/explore-findings.md" << 'EOF'
# Explore Findings

- **Topic**: test
- **Mode**: full
- **Date**: 2026-06-28
- **Version**: 99

## Summary

test summary

## Recommendation

**推荐 A** — reason
EOF

  EXPLORE_FILE="openspec/explore-findings.md"
  [ -f "$EXPLORE_FILE" ]

  VERSION=$(grep "Version" "$EXPLORE_FILE" | grep -oE '[0-9]+')
  [ "$VERSION" -gt 1 ]

  grep -q "test summary" "$EXPLORE_FILE"
  grep -q "推荐 A" "$EXPLORE_FILE"
}

@test "end-to-end: full mode → detect → context injection" {
  cat > "$TMP_DIR/input.yaml" << 'EOF'
topic: "端到端集成"
summary: "E2E 测试完整流程"
options:
  - name: "方案 A"
    pros:
      - "好"
    cons:
      - "贵"
    effort: "1周"
  - name: "方案 B"
    pros:
      - "快"
    cons:
      - "不完美"
    effort: "2天"
recommendation: "方案 B"
reason: "时间优先"
EOF

  run bash "$SPECULATE_SCRIPT" \
    --mode full \
    --from-file "$TMP_DIR/input.yaml" \
    --output "$TMP_DIR/openspec/explore-findings.md"

  [ "$status" -eq 0 ]

  EXPLORE_FILE="openspec/explore-findings.md"
  [ -f "$EXPLORE_FILE" ]

  grep -q "^# Explore Findings" "$EXPLORE_FILE"
  grep -q "^## Summary" "$EXPLORE_FILE"
  grep -q "^## Options" "$EXPLORE_FILE"
  grep -q "^## Recommendation" "$EXPLORE_FILE"
  grep -q "方案 B" "$EXPLORE_FILE"
  grep -q "时间优先" "$EXPLORE_FILE"

  EXPLORE_SUMMARY=$(sed -n '/^## Summary/,/^## Options/p' "$EXPLORE_FILE" | head -n -1 | tail -n +3)
  EXPLORE_REC=$(sed -n '/^## Recommendation/,$ p' "$EXPLORE_FILE" | tail -n +3)

  echo "Injected Summary: $EXPLORE_SUMMARY"
  echo "Injected Recommendation: $EXPLORE_REC"
  echo "$EXPLORE_SUMMARY" | grep -q "E2E"
  echo "$EXPLORE_REC" | grep -q "方案 B"
}
